# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: bluestarburst
has_binder: true
has_settings: false
kind: frontend
labextension_name: tensordock
project_short_description: A JupyterLab extension.
python_name: tensordock
repository: ''
test: true

